### ISSUE TITLE
Option for using ObjectLiteral or else to allow Entities not extended from BaseEntity

### ISSUE THREAD

**Issue by tkahng** [woowabros/nestjs-library-crud#376]
Currently our entities are not extended from BaseEntity. is there a reason the type is BaseEntity for the services?
ive browsed through the source code and didnt find anything that would break if it allowed regular Entities.

**Comment by jiho-kr** [comment]
hi tkahng

Right
It is not using `ActiveRecord Pattern`, so there is no problem with not extended from BaseEntity.

The BaseEntity Type is being simply used for the purpose `that is Entity`.

**Comment by jiho-kr** [comment]
It means an interface of the form `InjectRepository` in `@nestjs/typeform`.

https://github.com/nestjs/typeorm/blob/master/lib/interfaces/entity-class-or-schema.type.ts#L3

I think it's better than managing separate types in CRUD.

**Comment by jiho-kr** [comment]
I found the use of the `Active Record Pattern` in the code.

This will be fixed in https://github.com/woowabros/nestjs-library-crud/pull/377

**Comment by jiho-kr** [comment]
https://github.com/woowabros/nestjs-library-crud/pull/384

**Comment by jiho-kr** [comment]
resolved in [0.9.0](https://github.com/woowabros/nestjs-library-crud/releases/tag/0.9.0)
