### ISSUE TITLE
Error: Cannot find Entity name from TypeORM

### ISSUE THREAD

**Issue by mattnieland** [woowabros/nestjs-library-crud#383]
Hello, 

First off love the library and am excited to use it in a new project my company is working on.  But I'm having some trouble with my user entity and I can't figure out why.

I'm following your guide, except my user is in a company NPM package and looks like this:
![image](https://github.com/woowabros/nestjs-library-crud/assets/10760125/b04fa913-348f-4b42-99c2-226cbdaba275)

Extended from a BaseEntity which also extends BaseEntity:
![image](https://github.com/woowabros/nestjs-library-crud/assets/10760125/8bb5ff15-585e-491e-98f6-60bca7c6a85e)

Here's the error I'm getting:
![image](https://github.com/woowabros/nestjs-library-crud/assets/10760125/993b680b-fc9f-4db5-b241-2f264f0c7b7f)

package.json deps:

`{
    "@liaoliaots/nestjs-redis": "^9.0.5",
    "@nestjs-library/crud": "^0.8.8",
    "@nestjs/bull": "^10.0.1",
    "@nestjs/common": "^10.2.10",
    "@nestjs/config": "^3.1.1",
    "@nestjs/core": "^10.2.10",
    "@nestjs/jwt": "^10.2.0",
    "@nestjs/passport": "^10.0.2",
    "@nestjs/platform-express": "^10.2.10",
    "@nestjs/swagger": "^7.1.16",
    "@nestjs/throttler": "^5.0.1",
    "@nestjs/typeorm": "^10.0.1",
    "@sentry/node": "^7.85.0",
    "@sentry/tracing": "^7.85.0",
    "@swc/jest": "^0.2.29",
    "axios": "^1.6.2",
    "bcrypt": "^5.1.1",
    "bull": "^4.11.5",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "cookie": "^0.6.0",
    "cookie-parser": "^1.4.6",
    "express": "^4.18.2",
    "fast-xml-parser": "^4.3.2",
    "fastify": "^4.24.3",
    "joi": "^17.11.0",
    "jsonwebtoken": "^9.0.2",
    "nanoid": "3",
    "nestjs-paginate": "^8.5.0",
    "nestjs-pino": "^3.5.0",
    "passport-apple": "^2.0.2",
    "passport-facebook": "^3.0.0",
    "passport-google-oauth20": "^2.0.0",
    "passport-jwt": "^4.0.1",
    "pg": "^8.11.3",
    "pino": "^8.16.2",
    "pino-http": "^8.5.1",
    "pino-webpack-plugin": "^2.0.0",
    "rxjs": "^7.8.1",
    "supertest": "^6.3.3",
    "typeorm": "^0.3.17"
  }`
  
  I'd appreciate any support you can lend since I feel I'm close and I don't wanna crud everything manually!

**Comment by Pigrabbit** [comment]
Hi, would you try to provide name in `@Entity()` decorator which decorates your `User` entity as below?

```ts
@Entity('user')
export class User extends BaseEntity {
  // ... 
}
```

**Comment by jiho-kr** [comment]
hi, @mattnieland 

It has been changed to be used without defining the entity name . ( https://github.com/woowabros/nestjs-library-crud/pull/399 )


You will be able to check if this is the problem and close the issue.

**Comment by jiho-kr** [comment]
include [0.10.1](https://github.com/woowabros/nestjs-library-crud/releases/tag/0.10.1)
