### ISSUE TITLE
add support for table inheritance

### ISSUE THREAD

**Issue by chihabhajji** [woowabros/nestjs-library-crud#389]
Hello, Jeongmin Lee, jiho-kr , all the woowabros, and all the maintainers of this repo, first of all thank you for this amazing library.
I'm a novice in nestjs and TypeORM especially, so id really appreciate if someone can guide me on how i can help resolve the issue of not being able to use table inheritance. 
The route factory is unable to resolve the entity name (i tried matching if the type of the table is not entity-child, but that led to "Cannot read properties of undefined (reading 'ownColumns')").
I started with unit tests (read-many only for now).
PR: #388

**Comment by jiho-kr** [comment]
hi @chihabhajji 

I checked this issue(https://github.com/woowabros/nestjs-library-crud/issues/389) and PR(https://github.com/woowabros/nestjs-library-crud/pull/388).

It has been confirmed that `ChildEntity` is not currently supported. 
I have added a new PR(https://github.com/woowabros/nestjs-library-crud/pull/390) in place of the PR you contributed to support `ChildEntity` and hope this helps you.

**Comment by chihabhajji** [comment]
thank you ^^
