### ISSUE TITLE
[Suggestion] Support ability to inject custom Connection 

### ISSUE THREAD

**Issue by chihabhajji** [woowabros/nestjs-library-crud#407]
I'm loving the library so far, but in order to take to take full advantage of it, it would be nice if we can provide support for injecting a custom TypeORM connection in order to implement multitenancy

**Comment by jiho-kr** [comment]
You can manage it in your `module` and `service(extend CrudService)`

Because the library uses typeorm connection through `Respository of CrudService`.

**Comment by chihabhajji** [comment]
thank you ^^
