### ISSUE TITLE
[Issue]: Offset pagination - Offset skips first entity

### ISSUE THREAD

**Issue by chihabhajji** [woowabros/nestjs-library-crud#432]
Hello,

when using offset pagination it skips the first record in the database.

possible fixes are either allowing the offset to be 0 or using offset -1

**Comment by jiho-kr** [comment]
Hi @chihabhajji 

I tried to check it through unit-test(https://github.com/woowabros/nestjs-library-crud/pull/433), but I couldn't reproduce it.

Can you give me more information?

**Comment by chihabhajji** [comment]
Hello @jiho-kr , gladly, here is my database, it has one record for the purpose of this test
![image](https://github.com/woowabros/nestjs-library-crud/assets/35853327/53d2537f-cdd9-40f8-85a0-847d47bd9f0b)
when i try the endpoint with 10 limit and offset 1 i get the following 
![image](https://github.com/woowabros/nestjs-library-crud/assets/35853327/37d5a132-370c-4399-85ad-2fefa08fc72a)
![image](https://github.com/woowabros/nestjs-library-crud/assets/35853327/e489939a-b9ec-402d-aed2-9302f3247209)
the metadata has total 1 but the record is not returned.
and after i add a user and run the same query i get the following 
![image](https://github.com/woowabros/nestjs-library-crud/assets/35853327/29cf49d4-ca78-43cf-a9ce-ae3ec4437a50)
this is my controller
`@ApiTags('users')
@ApiBearerAuth()
@ApiOAuth2(['email', 'profile'])
@Crud({
    entity: User,
    routes: {
        readMany: {
            relations: ['profile'],
            paginationType: 'offset',
            numberOfTake: 10,
            softDelete: false,
            sort: 'ASC',
            swagger: {
                response: DepopulatedUserInfoDTO,
            },
            decorators: [ApiQuery({ name: 'role', type: String, enum: ERole })],
            exclude: ['password', '_id', 'deletedAt'],
        },
        readOne: {
            exclude: ['password'],
            relations: ['profile', 'organizations', 'memberOrganizations'],
            swagger: {
                response: OmitType(User, ['password', 'deletedAt']),
            },
        },
        search: {
            relations: ['profile'],
            paginationType: 'offset',
            numberOfTake: 10,
            swagger: {
                response: DepopulatedUserInfoDTO,
            },
            exclude: ['password', '_id', 'deletedAt'],
        },
    },
    only: [Method.READ_MANY, Method.READ_ONE, Method.UPDATE, Method.SEARCH],
})
@Controller('users')
export class UsersController {
    // noinspection JSUnusedLocalSymbols
    constructor(private readonly crudService: UsersService) {}
}
`

**Comment by jiho-kr** [comment]
Hi, @chihabhajji 

Because you set the offset to 1, the data is searched from the second time.
You should either not set offset or use 0.

This [article](https://www.postgresql.org/docs/current/queries-limit.html) might be helpful for you.

**Comment by chihabhajji** [comment]
Yes i am aware of that, thats why my issue title says allow offset to be 0, because 0 is not accepted

**Comment by jiho-kr** [comment]
aha I get it, i'll check `0 is not accepted`

**Comment by chihabhajji** [comment]
![image](https://github.com/woowabros/nestjs-library-crud/assets/35853327/9201d1f4-0e83-4dc8-a771-d8657eb63352)

**Comment by jiho-kr** [comment]
https://github.com/woowabros/nestjs-library-crud/releases/tag/0.10.2

**Comment by chihabhajji** [comment]
thank you ^^
