### ISSUE TITLE
[Issue]: embedded properties are always null in readMany and readOne

### ISSUE THREAD

**Issue by chihabhajji** [woowabros/nestjs-library-crud#440]
Hello again woowabros, as always, thank you for this gold mine.

As for the issue, as described by the title, when using [embedded entities](https://orkhan.gitbook.io/typeorm/docs/embedded-entities), they are never returned in readOne and readMany, i tried adding them to the relation property but that didnt work too.

If unable to reproduce i can share a reporudction repo.

**Comment by jiho-kr** [comment]
Okay I will check on this.
It`s helping me with pattern I don't used. thanks

**Comment by chihabhajji** [comment]
thank you ^^
