### ISSUE TITLE
[Issue]: using .save instead of .create and .update is triggering @BeforeInsert and @AfterInsert subscriber

### ISSUE THREAD

**Issue by chihabhajji** [woowabros/nestjs-library-crud#442]
Hello once again, as always, thank you for the amazing work and swift response!

After some digging around, i found out that typeorm .save method going to always trigger the @BeforeInsert @AfterInsert hooks, so i was wondering if you can modify the crud.service to use .create and .update methods respectively.

If you guys see this modification fits the repo, i can submit a PR

**Comment by jiho-kr** [comment]
Hi, @chihabhajji 

That's the intended behavior. 
Whenever an entity changes, @BeforeInsert @AfterInsert should be triggered.

**Comment by chihabhajji** [comment]
id like to disagree because by convention AfterCreate semnatically means after creating a new entity that didnt exist, and AfterUpdate means post updating an existing entity, think about seperating logic for creating a slug once that shouldnt change since it will be used as id, and update a user password using password both on BeforeCreate and BeforeUpdate.
If you guys still think that is the intended behavior, can i get a suggestion for seperating listeners

**Comment by jiho-kr** [comment]
hi, @chihabhajji   
I understood that you have services implemented through listeners, and that the crud library expects these listeners not to be triggered. Is right?

There is options for listeners and subscribers in saveOptions. [link](https://github.com/typeorm/typeorm/blob/83567f533482d0170c35e2f99e627962b8f99a08/docs/repository-api.md?plain=1#L407)

I can add new option(listeners?: boolean)' by method in the 'decorator' to make it controllable, what do you think?

e.g)
```
@Crud({
    entity: TestEntity,
    routes: { [Method.DELETE]: { listeners: false } },
})
```

**Comment by jiho-kr** [comment]
https://github.com/woowabros/nestjs-library-crud/pull/448

**Comment by chihabhajji** [comment]
thank you ^^
