### ISSUE TITLE
[Issue] Exception is not instance of HttpException

### ISSUE THREAD

**Issue by JadenKim-dev** [woowabros/nestjs-library-crud#500]
Hi there, I have some question about exception occurred in this library.
Is there a reason for the exception thrown by the library is not instance of HttpException?

It seems that if some exception occurs while processing the request, it responses 500 internal server error, even when the exception is instance of HttpException. (ex. NotFoundException, UnprocessableEntityException,  ...)

For example, if I request not existing entity data with route like `/user/999`, it responses 500.

```json
{
    "statusCode": 500,
    "message": "Internal server error"
}
```

NestJS default ExceptionFilter catch HttpException, so I expected it works, but it didn't.
I had to define my own ExceptionFilter that catches all Error, and apply it by using `decorators` option of `@Crud`.

```ts
@Crud({
  entity: User,
  routes: {
    [Method.READ_ONE]: {
      decorators: [UseFilters(new HttpExceptionFilter())],
    }
  }
})
```

In the catch method, I logged to check if the exception is instance of HttpException, and it says it is not instance of HttpException.

```ts
@Catch(Error)
export class HttpExceptionFilter implements ExceptionFilter {
  catch(exception: HttpException, host: ArgumentsHost) {
    console.log(exception instanceof HttpException);  // false
    console.log(exception.name);  // 'NotFoundException'
    const ctx = host.switchToHttp();
    const response = ctx.getResponse<Response>();
    const status = exception.getStatus();  // it works, so it has properties of HttpException

    response.status(status).json({
      statusCode: status,
      message: "HttpException occurred",
    });
  }
}
```

Why is this happening?
If possible, I want to use default exception filter of NestJS.

**Comment by jiho-kr** [comment]
Hi @JadenKim-dev 

try changing the version of `@nestjs/common`(your application) to @nestjs/common version of crud(usage curd library)?

if version of `@nestjs/common` is different, `HttpException` may not be as expected.
I think there is a change in the HttpException when changing `@nestjs/common` versions.

**Comment by JadenKim-dev** [comment]
@jiho-kr Thank you for your quick reply!
I upgraded version of NestJS from 9.xx to 10.xx, and now it works.
