### ISSUE TITLE
[Regression] OpenAPI generation from using OmitType / PickType / IntersectionType

### ISSUE THREAD

**Issue by chihabhajji** [woowabros/nestjs-library-crud#558]
The PR that removed the entity names when using swagger bodies made it so that all the generated types have the same name, making OpenAPI generators unable to infer the schemas

![image](https://github.com/woowabros/nestjs-library-crud/assets/35853327/58f0260a-ca87-4d61-ac31-46f5d72fd972)
First line is 0.12.0 , second line is 0.12.4

you can add test cases using https://github.com/7nohe/openapi-react-query-codegen or any OpenAPI generator

**Comment by jiho-kr** [comment]
thanks for your report.

I think it's a side effect of https://github.com/woowabros/nestjs-library-crud/pull/546,

I'll take look when I have some free time this week

**Comment by jiho-kr** [comment]
hi @chihabhajji

Thank you for reporting this.

I fixed it in https://github.com/woowabros/nestjs-library-crud/pull/564 and released [0.12.5](https://github.com/woowabros/nestjs-library-crud/releases/tag/0.12.5)

**Comment by chihabhajji** [comment]
even after upgrading to 0.12.5 i'm still running into the same issue, i can drop the generated output on discord or you can try the lib using https://api.finvo.fr/docs/yaml

**Comment by chihabhajji** [comment]
after further investigation its because every controller has the same operationId which is the reserved functions, for some reason swagger ommitted the controller ApiTag and controller names

**Comment by chihabhajji** [comment]
confirmed by debugging swagger's operationIdFactory function which resulted in the controllerKey param to be an empty string

**Comment by jiho-kr** [comment]
hi @chihabhajji 

Is this an issue with the name of the DTO using OmitType / PickType / IntersectionType  not being used as defined?

https://github.com/woowabros/nestjs-library-crud/blob/main/spec/exclude-swagger/exclude-swagger-resonse-name.spec.ts

**Comment by chihabhajji** [comment]
no, rather the controllerKey being the same for all reserved methods, since they omit the operation id for some reason when using swagger, so now all operations, instead of being prefixed by the controller name, are now prefixed by an empty string,

kindly refer to https://api.finvo.fr/docs/yaml and you'll notice all the operation ids are the reserved function names thus making them not unique

**Comment by jiho-kr** [comment]
Can you share your code with CRUD defined instead of [api.finvo.fr/docs/yaml](https://api.finvo.fr/docs/yaml)?

**Comment by chihabhajji** [comment]
the whole repo?

**Comment by jiho-kr** [comment]
I'm not sure what your issue is

**Comment by chihabhajji** [comment]
`@ApiTags('invoices')
@Controller('invoices')
@Crud({
    entity: InvoiceEntity,
    only: ['create', 'delete', 'search', 'readOne', 'readMany'],
    logging: true,
    routes: {
        readMany: {
            softDelete: false,
            paginationType: PaginationType.OFFSET,
            relations: false,
            exclude: [
                'client',
                'products',
                'finalizedData',
                'avoire',
                'notes',
                'previousUnpaidBalanceCurrency',
                'totalDiscountCurrency',
                'historiques',
                'deletedAt',
            ] as (keyof InvoiceEntity)[],
        },
        create: {
            author: {
                filter: 'user.username',
                property: 'createdBy',
            },
            exclude: excludedFields,
            swagger: {
                body: PickType(InvoiceEntity, ['invoiceUrl', 'documentKind']),
                response: PickType(InvoiceEntity, [
                    'id',
                    'invoiceUrl',
                    'documentKind',
                    'processingStatus',
                    'paymentStatus',
                ] as (keyof InvoiceEntity)[]),
            },
            listeners: true,
        },
        delete: {
            softDelete: true,
        },
        readOne: {
            relations: readOneRelations,
            swagger: {
                response: IntersectionType(InvoiceEntity, DeletedAtField),
            },
            softDelete: false,
            exclude: [],
        },
        search: {
            paginationType: PaginationType.OFFSET,
            relations: false,
            exclude: [
                'client',
                'products',
                'finalizedData',
                'avoire',
                'notes',
                'previousUnpaidBalanceCurrency',
                'totalDiscountCurrency',
                'historiques',
                'deletedAt',
            ] as (keyof InvoiceEntity)[],
            softDelete: false,
        },
    },
})
export class InvoicesController extends TenantedController .... rest omitted`

`@ApiHeader({
    name: TENANT_HEADER,
    required: true,
    description: 'Organization slug (tenancy)',
    allowEmptyValue: false,
})
@ApiPreconditionFailedResponse({
    description: 'Thrown when tenant is not provided or is invalid',
})
@UseGuards(IsOrganizationOwnerOrMemberGuard)
@ApiBearerAuth()
export class TenantedController {}`

the operationId factory method for swagger
`function operationIdFactory(controllerKey: string, methodKey: string) {
    console.log('controllerKey', controllerKey);
    console.log('methodKey', methodKey);
    // Since crud package uses the same controller  for all methods, we need to strip the reserved word from the method name
    const strippedMethodKey = methodKey.replace('reserved', '');
    // optional, so front devs have less verbose names
    const strippedControllerKey = controllerKey.replace('Controller', '');
    return `${strippedControllerKey}${capitalize(strippedMethodKey)}`;
}`
the issue is,
for non crud-library routes, the controllerKey shows up correct, for example AuthController,
but for crud library routes, the controllerKey is always an empty string

**Comment by jiho-kr** [comment]
i see, It seems like a different issue.

Can you check the version of the @nestjs library?

In 0.12.1, the @nestjs library was bump up.

https://github.com/woowabros/nestjs-library-crud/releases/tag/0.12.1

```
build(deps): bump @nestjs/common from 10.3.7 to 10.3.8 (https://github.com/woowabros/nestjs-library-crud/commit/6b0c6d06f22797a0d13638e783f075a854312820)
build(deps): bump @nestjs/swagger from 7.3.0 to 7.3.1 (https://github.com/woowabros/nestjs-library-crud/commit/e54cde921a9a707c72e1c77bce4c966b1a241079)

**Comment by chihabhajji** [comment]
"@nestjs/common": "^10.3.9",
    "@nestjs/config": "^3.2.2",
    "@nestjs/core": "^10.3.9",
    "@nestjs/jwt": "^10.2.0",
    "@nestjs/passport": "^10.0.3",
    "@nestjs/platform-express": "^10.3.9",
    "@nestjs/swagger": "^7.3.1",

**Comment by chihabhajji** [comment]
i just updated them earlier to check if a version mismatch was the issue, but even downgrading and using v 0.12.0 resulted in the same issue

**Comment by jiho-kr** [comment]
If you have the same issue in 0.12.0, I don't think it's a DTO name issue.

Are you sure your issue is a dto name issue?

> The PR that removed the entity names when using swagger bodies made it so that all the generated types have the same name, making OpenAPI generators unable to infer the schemas

**Comment by chihabhajji** [comment]
the initial issue is a miss diagnosis by me, i thought the issue was caused by the #564 pr because after it the generated openapi schemas all had the same name 

but after further investigation, it turns out the controllers annotated with @Crud all had the same controller prefix which is an empty string, thus making all the operation ids the same across all reserved method routes and ultimtely making the generated DTO's all have the same prefix

**Comment by jiho-kr** [comment]
I understand that it's not a DTO name issue.

But I still don't understand what your issuse is.

Can you pick out which part of [api.finvo.fr/docs/yaml](https://api.finvo.fr/docs/yaml) is the issue?


I don't know what your issue is when I only see '/api/tenanted/invoices/send-Invoice' and '  /api/tenanted/invoices/stats/{documentKind}'.

```
/api/tenanted/invoices/send-Invoice:
    post:
      operationId: SendInvoice
      parameters:
        - name: x-tenant-id
          in: header
          description: Organization slug (tenancy)
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendInvoiceDto'
      responses:
        '201':
          description: ''
        '412':
          description: Thrown when tenant is not provided or is invalid
      tags:
        - invoices
      security:
        - bearer: []
  /api/tenanted/invoices/stats/{documentKind}:
    get:
      operationId: GetInvoicesStatsByKind
      parameters:
        - name: x-tenant-id
          in: header
          description: Organization slug (tenancy)
          required: true
          schema:
            type: string
        - name: documentKind
          required: true
          in: path
          schema:
            enum:
              - sell
              - buy
              - estimate
              - credit
              - unknown
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoicesStatsDTO'
        '412':
          description: Thrown when tenant is not provided or is invalid
      tags:
        - invoices
      security:
        - bearer: []
```

**Comment by jiho-kr** [comment]
ah! 

Are you talking about this?
> description: Organization slug (tenancy)

**Comment by jiho-kr** [comment]
https://github.com/woowabros/nestjs-library-crud/pull/545 is included 0.12.3

> i just updated them earlier to check if a version mismatch was the issue, but even downgrading and using v 0.12.0 resulted in the same issue


Is there the same issue in '0.12.0'?

```
[Release 0.12.3](https://github.com/woowabros/nestjs-library-crud/releases/tag/0.12.3)

Changelog:

feat: update eslint (https://github.com/woowabros/nestjs-library-crud/pull/547) (https://github.com/woowabros/nestjs-library-crud/commit/69b4568063fd609620c3d688ffbb3503055b22ad)
refactor: improve validation for search route and refactor test code (https://github.com/woowabros/nestjs-library-crud/pull/548, @JadenKim-dev ) (https://github.com/woowabros/nestjs-library-crud/commit/19db83590a227eef8bdf47c50b1526da6d4219b8)
feat: changed request body schema name when using omitted/picked type (https://github.com/woowabros/nestjs-library-crud/pull/546, @JadenKim-dev ) (https://github.com/woowabros/nestjs-library-crud/commit/a103a02b85c05e68924af2f69cb2ec0ef0573aa1)
feat: add validation to check if CrudService is included as member of controller (https://github.com/woowabros/nestjs-library-crud/pull/545, @JadenKim-dev ) (https://github.com/woowabros/nestjs-library-crud/commit/87b7311cda91b28f32ef0f66bf9a2709216d5ee0)
build(deps-dev): bump release-it from 17.2.1 to 17.3.0 (https://github.com/woowabros/nestjs-library-crud/pull/540) (https://github.com/woowabros/nestjs-library-crud/commit/4abf4d450affd2fcc87a686eaf8d82b204e68e20)
build(deps-dev): bump @types/lodash from 4.17.1 to 4.17.4 (https://github.com/woowabros/nestjs-library-crud/pull/541) (https://github.com/woowabros/nestjs-library-crud/commit/d852eee1a850278c189b8b746642d805ade8ed1f)
build(deps-dev): bump @types/node from 20.12.11 to 20.12.12 (https://github.com/woowabros/nestjs-library-crud/pull/542) (https://github.com/woowabros/nestjs-library-crud/commit/4ae794665eb90e6cdce5fb2f9e54b9898145174a)
```

**Comment by JadenKim-dev** [comment]
It seems that the problem needs to be further clarified, but the operationId needs to be not an empty string, so I fixed it in #567.
Now the controller key is name of original controller.

**Comment by jiho-kr** [comment]
Is this an issue related to https://github.com/woowabros/nestjs-library-crud/pull/567 ?

**Comment by jiho-kr** [comment]
@chihabhajji , 
Can you check with https://github.com/woowabros/nestjs-library-crud/releases/tag/0.12.6?

**Comment by chihabhajji** [comment]
![image](https://github.com/woowabros/nestjs-library-crud/assets/35853327/07425909-12c3-45a1-86d2-e22396e91898)
can confirm everything works as expected, thank you @jiho-kr sorry for the misunderstanding

**Comment by jiho-kr** [comment]
thank you for interest @chihabhajji
