### ISSUE TITLE
Duplicated options for search: take, limit.

### ISSUE THREAD

**Issue by JadenKim-dev** [woowabros/nestjs-library-crud#571]
Hello, there!

I found that there are redundant options serving the same function in search route - `take`, `limit`.
It seems that the 'take' option was already existing, and the 'limit' option was added when pagination was supported for search route.
Currently, when both 'limit' and 'take' options exist simultaneously, 'limit' overrides 'take.' 
[related code](https://github.com/woowabros/nestjs-library-crud/blob/main/src/lib/request/read-many.request.ts#L130)

I found this part to be somewhat confusing. 
Is there a reason why the two options must exist together?
It would be good to keep only one of the two options, if that's okay.

**Comment by JadenKim-dev** [comment]
Currently I worked to make swagger docs for search include pagination info in request body. #570 
This has led to both `offset` and `limit` being included in the request body, but it would be better to keep just one of them.

<img width="229" alt="screenshot" src="https://github.com/woowabros/nestjs-library-crud/assets/61740850/7ef6843a-bd00-4138-ad30-b4e6408fc8a3">

**Comment by jiho-kr** [comment]
i take looked at `SearchRequestInterceptor` and `RequestSearchDto`

in Search method, `limit` is not provided.

I think it should only be `take` in Search method.

i'll take a look at where the `limit` is added with swagger docs

**Comment by jiho-kr** [comment]
In offset pagination,`limit` and `offset` are used to patch the next page.

in cursor pagination, `nextCursor` is used. 

`take and limit` are not the same role.

**Comment by JadenKim-dev** [comment]
It seems that `_findOptions.take` is overwritten by `pagination.limit` in `ReadManyRequest.generate()` - [related code](https://github.com/woowabros/nestjs-library-crud/blob/main/src/lib/request/read-many.request.ts#L130)
`setTake()` first set `_findOptions.take` by take option, and `generate()` overwrite it by limit option - [related code](https://github.com/woowabros/nestjs-library-crud/blob/main/src/lib/interceptor/search-request.interceptor.ts#L85)

**Comment by JadenKim-dev** [comment]
`limit` is added in swagger docs after my work(#570), so that search include pagination option in request body.
When I did API testing, the limit option also worked correctly.

- only take specified in request.body -> take is applied
- only limit specified in request.body -> limit is applied
- take, limit both specified in request.body -> limit is applied

**Comment by jiho-kr** [comment]
i see,

The two purposes seem to be different, but you think it's a good idea to combine them, right?

**Comment by JadenKim-dev** [comment]
Is it originally intended that `take` is used for `cursor pagination` and `limit` is used for `offset pagination`? 
It seems that both are currently being used interchangeably in both contexts. 
If possible, I think it would be better to either clearly separate the two for their respective uses, or unify them into a single option.

**Comment by jiho-kr** [comment]
I think the body provided on the first page and the body used on the next page should be provided separately(like oneof). how do you think?

**Comment by jiho-kr** [comment]
I think we need to think about whether the functions of take and limit conflict.

**Comment by JadenKim-dev** [comment]
> I think the body provided on the first page and the body used on the next page should be provided separately(like oneof). how do you think?

I agree with it. 
Since many options can be omitted after first pagination, it would be good if we could differentiate these cases in the Swagger docs.

**Comment by JadenKim-dev** [comment]
> (in function) I think we need to think about whether the functions of take and limit conflict.
> like Offset pagination does not support take...

After further detailed testing of the API, it was observed that:

In cursor pagination, only the ‘take’ option is used, and the ‘limit’ option is ignored, so no additional works are needed.
In offset pagination, both ‘take’ and ‘limit’ are used simultaneously.

I would work on it in a future PR.
