### ISSUE TITLE
Internal Events

### ISSUE THREAD

**Issue by justindefodji** [woowabros/nestjs-library-crud#628]
Sometimes, It can be useful to produce an event after an action and do something else with that event!

I think handle this kind of process can be a great improvement.

Thanks

**Comment by jiho-kr** [comment]
In nestjs, it can use interceptors to accomplish this purpose.

You can see how to use them in '[spec/request-interceptor](https://github.com/woowabros/nestjs-library-crud/tree/main/spec/request-interceptor)' and '[spec/response-interceptor](https://github.com/woowabros/nestjs-library-crud/tree/main/spec/response-interceptor)'

**Comment by justindefodji** [comment]
Thank you @jiho-kr
