### ISSUE TITLE
README instructions do not work as expected

### ISSUE THREAD

**Issue by ho-1** [woowabros/nestjs-library-crud#71]
I may have made a mistake, but I was able to resolve the issue by making the following modifications.

### Step 1: Define a TypeORM entity

not work:
```
...
@Entity()
export class User {
...
```
You may encounter an error message `error TS2344: Type 'User' does not satisfy the constraint 'BaseEntity'.` or `Error: Cannot find Entity name from TypeORM`.

try this:
```
import { 
 ...,
 BaseEntity 
} from "typeorm";

@Entity('user')
export class User extends BaseEntity {
...
```

### Step 2: Create Service and Controller

not work:
```
import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { CrudService } from '@nestjs-library/crud';
import { Repository } from 'typeorm';

import { User } from './user.entity';

@Injectable()
export class UserService extends CrudService<User> {
    constructor(@InjectRepository(BaseEntity) repository: Repository<User>) {
        super(repository);
    }
}
```

try this:
```
import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { CrudService } from '@nestjs-library/crud';
import { Repository } from "typeorm";

import { User } from './user.entity';

@Injectable()
export class UsersService extends CrudService<User> {
  constructor(@InjectRepository(User) repository: Repository<User>) {
    super(repository);
  }
}
```
- Change the parameter of the InjectRepository decorator from `BaseEntity` to `User`

**Comment by jiho-kr** [comment]
Thanks for post, I will `fix the Readme` in the near future.

### Step 1: Define a TypeORM entity

You're right.  Entity expects to inherit from BaseEntity.

### Step 2: Create Service and Controller

You're right.  `InjectRepository` follows TypeORM.

```
export declare const InjectRepository: (entity: EntityClassOrSchema, dataSource?: string) => ReturnType<typeof Inject>;
```

**Comment by jiho-kr** [comment]
I've written a [PR](https://github.com/woowabros/nestjs-library-crud/pull/72) for a fix and thanks again.
